on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'COPYING'
      - 'website/**'
      - '.github/*.md'
      - '.github/FUNDING.yml'

name: Build Code
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - name: Checkout code ðŸ‘‹
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Install Go ðŸ—³
      uses: ./.github/workflows/composite/bootstrap-go
    - name: Run GoReleaser ðŸš€
      uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b
      with:
        distribution: goreleaser
        version: latest
        args: build --rm-dist --snapshot --skip-post-hooks --skip-before
        workdir: src
    - name: Archive production artifacts
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: builds
        retention-days: 1
        path: |
          src/dist
