on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'COPYING'
      - 'website/**'
      - '.github/*.md'
      - '.github/FUNDING.yml'

name: Build Code
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - name: Checkout code ðŸ‘‹
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
    - name: Install Go ðŸ—³
      uses: ./.github/workflows/composite/bootstrap-go
    - name: Run GoReleaser ðŸš€
      uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8
      with:
        distribution: goreleaser
        version: latest
        args: build --rm-dist --snapshot --skip-post-hooks --skip-before
        workdir: src
    - name: Archive production artifacts
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
        name: builds
        retention-days: 1
        path: |
          src/dist
