on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'COPYING'
      - 'website/**'
      - '.github/*.md'
      - '.github/FUNDING.yml'

name: Build Code
jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - name: Checkout code ðŸ‘‹
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - name: Install Go ðŸ—³
      uses: ./.github/workflows/composite/bootstrap-go
    - name: Run GoReleaser ðŸš€
      uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200
      with:
        distribution: goreleaser
        version: latest
        args: build --clean --snapshot --skip=post-hooks --skip=before
        workdir: src
    - name: Archive production artifacts
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874
      with:
        name: builds
        retention-days: 1
        path: |
          src/dist
