on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'COPYING'
      - 'website/**'
      - '.github/*.md'
      - '.github/FUNDING.yml'

name: Build Code
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - name: Checkout code ðŸ‘‹
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - name: Install Go ðŸ—³
      uses: ./.github/workflows/composite/bootstrap-go
    - name: Run GoReleaser ðŸš€
      uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757
      with:
        distribution: goreleaser
        version: latest
        args: build --rm-dist --snapshot --skip-post-hooks --skip-before
        workdir: src
