name: Delete Store Submission

on:
  workflow_dispatch:

jobs:
  delete_submission:
    name: Delete Store Submission
    runs-on: ubuntu-latest
    steps:
      - name: Configure Store Credentials ğŸ”‘
        uses: jandedobbeleer/store-submission@submission-status
        with:
          command: configure
          type: win32
          seller-id: ${{ secrets.SELLER_ID }}
          product-id: ${{ secrets.PRODUCT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}

      - name: Delete Submission ğŸ—‘ï¸
        uses: jandedobbeleer/store-submission@submission-status
        with:
          command: delete
