name: Discord
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Changelog ğŸ“
        uses: sebastianpopp/discord-action@ba18c5aaa871acf97620c349fd76a187550f12eb
        with:
          webhook: ${{ secrets.CHANGELOG_WEBHOOK }}
          message: |
            ğŸ“¦ ${{ github.event.release.name }}

            ${{ github.event.release.body }}

            ${{ github.event.release.html_url }}
