name: Discord
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notes ğŸ“
        id: notes
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        with:
          result-encoding: string
          script: |
            notes = context.payload.release.body

            // replace all non-supported characters
            notes = notes.replaceAll('###', '')
            notes = notes.trim()
            return notes
      - name: Changelog ğŸ“
        uses: sebastianpopp/discord-action@4f2d5417bc61a79593304a62e71cd32427c17790
        with:
          webhook: ${{ secrets.CHANGELOG_WEBHOOK }}
          message: |
            ğŸ“¦ ${{ github.event.release.name }}

            ${{steps.notes.outputs.result}}

            ${{ github.event.release.html_url }}
