name: Discord
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Notes ğŸ“
        id: notes
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        with:
            result-encoding: string
            script: |
            notes = context.payload.release.body

            // replace all non-supported characters
            notes = notes.replaceAll('###',
            notes = notes.trim()
            return notes
      - name: Changelog ğŸ“
        uses: sebastianpopp/discord-action@ba18c5aaa871acf97620c349fd76a187550f12eb
        with:
          webhook: ${{ secrets.CHANGELOG_WEBHOOK }}
          message: |
            ğŸ“¦ ${{ github.event.release.name }}

            ${{steps.notes.outputs.result}}

            ${{ github.event.release.html_url }}
