name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
    - 'website/**'
    - 'themes/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          submodules: true
          persist-credentials: false
      - name: Install Go
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613
        with:
          go-version: 1.18
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 17.6.0
        # Create Kind cluster to have a Kubernetes context for cloud-native-azure theme
        # Images are defined on every Kind release
        # See https://github.com/kubernetes-sigs/kind/releases
      - name: Create k8s v1.23 Kind Cluster
        uses: helm/kind-action@9e8295d178de23cbfbd8fa16cf844eec1d773a07
        with:
          node_image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
          cluster_name: posh
      - name: Create Kubernetes namespace
        run: |
          kubectl create ns demo
      - name: Set default Kubernetes namespace
        run: |
          kubectl config set-context posh --namespace demo
      - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build oh-my-posh ðŸ”§
        run: |
          cd src
          go build -o ./bin/oh-my-posh
          cd ..
      - name: Render themes ðŸŽ¨
        run: |
          export PATH="$PWD/src/bin:$PATH"
          cd website
          npm install --legacy-peer-deps
          npm run themes
          cd ..
      - name: Build Docs And Deploy ðŸš€
        id: builddeploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_MEADOW_063E9BA03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/website" # App source code path
          api_location: "/website/api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
