name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "website/**"
      - "themes/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          submodules: true
          persist-credentials: false
      - name: Install Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version: 1.21
          cache-dependency-path: src/go.sum
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 20.9.0
        # Create Kind cluster to have a Kubernetes context for cloud-native-azure theme
        # Images are defined on every Kind release
        # See https://github.com/kubernetes-sigs/kind/releases
      - name: Create k8s v1.23 Kind Cluster
        uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced
        with:
          node_image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
          cluster_name: posh
      - name: Create Kubernetes namespace
        run: |
          kubectl create ns demo
      - name: Set default Kubernetes namespace
        run: |
          kubectl config set-context posh --namespace demo
      - uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build oh-my-posh ðŸ”§
        run: |
          cd src
          go build -o ./bin/oh-my-posh
          cd ..
      - name: Render themes ðŸŽ¨
        run: |
          export PATH="$PWD/src/bin:$PATH"
          cd website
          npm install
          npm run themes
          cd ..
      - name: Build Docs And Deploy ðŸš€
        id: builddeploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_MEADOW_063E9BA03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/website" # App source code path
          api_location: "/website/api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
