name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
    - 'website/**'
    - 'themes/**'

permissions:
      id-token: write
      contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          submodules: true
          persist-credentials: false
      - name: Install Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version: 1.20.2
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: 17.6.0
        # Create Kind cluster to have a Kubernetes context for cloud-native-azure theme
        # Images are defined on every Kind release
        # See https://github.com/kubernetes-sigs/kind/releases
      - name: Create k8s v1.23 Kind Cluster
        uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00
        with:
          node_image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
          cluster_name: posh
      - name: Create Kubernetes namespace
        run: |
          kubectl create ns demo
      - name: Set default Kubernetes namespace
        run: |
          kubectl config set-context posh --namespace demo
      - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Build oh-my-posh ðŸ”§
        run: |
          cd src
          go build -o ./bin/oh-my-posh
          cd ..
      - name: Render themes ðŸŽ¨
        run: |
          export PATH="$PWD/src/bin:$PATH"
          cd website
          npm install --legacy-peer-deps
          npm run themes
          cd ..
      - name: Build Docs And Deploy ðŸš€
        id: builddeploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_MEADOW_063E9BA03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/website" # App source code path
          api_location: "/website/api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
