name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
    - 'docs/**'
    - 'themes/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build oh-my-posh ðŸ”§
        run: |
          cd src
          go build -o ./bin/oh-my-posh
          cd ..
      - name: Render themes ðŸŽ¨
        run: |
          export PATH="$PWD/src/bin:$PATH"
          cd docs
          npm install
          npm run themes
          cd ..
      - name: Build Docs And Deploy ðŸš€
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_MEADOW_063E9BA03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/docs" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
