name: PowerShell
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}/packages/powershell
    steps:
    - name: Checkout code ðŸ‘‹
      uses: actions/checkout@v2
    - name: Pack & Push ðŸ“¦
      run: |
        $version = $env:GITHUB_REF.TrimStart("refs/tags/v")
        ./deploy.ps1 -ModuleVersion $version -Repository PSGallery -RepositoryAPIKey ${{ secrets.PSGALLERY_KEY }}
