name: Scoop
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}/packages/scoop
    steps:
    - name: Checkout code üëã
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Get release ‚¨áÔ∏è
      id: get_release
      uses: bruceadams/get-release@3a8733307b85cd96d52772b037617bd63d99522e
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Update Template ‚úçÔ∏è
      run: |
        $version = $env:GITHUB_REF.TrimStart("refs/tags/v")
        ./build.ps1 -Version $version
    - name: Upload artifacts üÜô
      uses: actions/github-script@c713e510dbd7d213d92d41b7a7805a986f4c5c66
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log('environment', process.versions);

          const fs = require('fs').promises;

          const { repo: { owner, repo }, sha } = context;
          console.log({ owner, repo, sha });

          for (let file of await fs.readdir('./packages/scoop/dist')) {
            console.log('uploading', file);

            await github.rest.repos.uploadReleaseAsset({
              owner, repo,
              release_id: ${{ steps.get_release.outputs.id }},
              name: file,
              data: await fs.readFile(`./packages/scoop/dist/${file}`)
            });
          }
